-- Admin
DROP SEQUENCE ADMIN_SQ;
DROP TABLE ADMIN_L;
DROP TABLE ADMIN;

CREATE TABLE ADMIN(
    aNO NUMBER(2) PRIMARY KEY,
    aID VARCHAR2(50) UNIQUE NOT NULL,
    aPW VARCHAR2(50) NOT NULL,
    aEMAIL VARCHAR2(50) NOT NULL,
    aNAME VARCHAR2(50) NOT NULL,
    aTEL VARCHAR2(50) NOT NULL,
    aLEVEL VARCHAR2(50) DEFAULT 0 REFERENCES ADMIN_L(aLEVEL),
    aRDATE DATE DEFAULT SYSDATE
);

-- ADMIN LEVEL
CREATE TABLE ADMIN_L(
    aLEVEL VARCHAR2(10) PRIMARY KEY,
    aLEVEL_NAME VARCHAR2(50)
);

CREATE SEQUENCE ADMIN_SQ MAXVALUE 99 NOCACHE NOCYCLE;

-- ADMIN LELVE DATA
INSERT INTO ADMIN_L VALUES(0, 'MANAGER');
INSERT INTO ADMIN_L VALUES(1, 'HEAD_MANAGER');
INSERT INTO ADMIN_L VALUES(2, 'MASTER');

SELECT * FROM ADMIN;
SELECT * FROM ADMIN_L;

commit;

