DROP TABLE BOARD_COMMENT;
DROP TABLE OWNERBOARD;
DROP TABLE OWNER;
DROP TABLE RESERVATION;

DROP SEQUENCE SEQ_R;
DROP SEQUENCE SEQ_OB;
DROP SEQUENCE SEQ_BC;
-- OWNERBOARD 시퀀스
CREATE SEQUENCE SEQ_OB
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;
-- BOARD_COMMENT 시퀀스
CREATE SEQUENCE SEQ_BC
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;
-- OWNER 테이블 생성
CREATE TABLE owner(
    oid VARCHAR(50) PRIMARY KEY,
    ONAME VARCHAR(50),
    OPW VARCHAR(50),
    OTEL VARCHAR(50),
    OEMAIL VARCHAR(50),
    OADDRESS VARCHAR(250),
    OBIRTH DATETIME,
    OGENDER VARCHAR(10)
); 

-- OWNERBOARD 테이블 생성
CREATE TABLE OWNERBOARD(
    BNO NUMBER(8) PRIMARY KEY,
    OID VARCHAR2(50) REFERENCES OWNER(OID),
    SNAME VARCHAR2(50),
    BLOC VARCHAR2(50),
    BTITLE VARCHAR2(50),
    BCONTENT VARCHAR2(4000),
    BPHOTO1 VARCHAR2(250),
    BPHOTO2 VARCHAR2(250),
    BPHOTO3 VARCHAR2(250),
    BPHOTO4 VARCHAR2(250),
    BPHOTO5 VARCHAR2(250),
    BHIT NUMBER(8),
    BDATE DATE DEFAULT SYSDATE
);
-- BOARD_COMMENT 테이블 생성
CREATE TABLE BOARD_COMMENT(
    CNO NUMBER(8) PRIMARY KEY,
    BNO NUMBER(8) REFERENCES OWNERBOARD(BNO),
    OID VARCHAR2(50) REFERENCES OWNER(OID),
    CCONTENT VARCHAR2(2000),
    CDATE DATE
);
-- RESERVATION SEQ
CREATE SEQUENCE SEQ_R
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;
    
-- RESERVATION 테이블 생성
CREATE TABLE RESERVATION(
    RNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(50) REFERENCES MEMBER(MID),
    SNO NUMBER(8) REFERENCES STORE(SNO),
    SNAME VARCHAR2(50),
    RDATE DATE NOT NULL,
    RTIME NUMBER(5) NOT NULL,
    RMEMBER NUMBER(5) NOT NULL
);
-----------------
SELECT RDATE, RTIME FROM RESERVATION WHERE SNO = 11 AND RDATE > SYSDATE -1;