DROP TABLE BOARD_COMMENT;
DROP TABLE OWNERBOARD;
DROP TABLE OWNER;
DROP SEQUENCE SEQ_OB;
DROP SEQUENCE SEQ_BC;
-- OWNERBOARD 시퀀스
CREATE SEQUENCE SEQ_OB
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;
-- BOARD_COMMENT 시퀀스
CREATE SEQUENCE SEQ_BC
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;
-- OWNER 테이블 생성
CREATE TABLE OWNER(
    OID VARCHAR2(50) PRIMARY KEY,
    ONAME VARCHAR2(50),
    OPW VARCHAR2(50),
    OTEL VARCHAR2(50),
    OEMAIL VARCHAR2(50),
    OADDRESS VARCHAR2(250),
    OBIRTH DATE,
    OGENDER VARCHAR2(10)
);
-- OWNERBOARD 테이블 생성
CREATE TABLE OWNERBOARD(
    BNO NUMBER(8) PRIMARY KEY,
    OID VARCHAR2(50) REFERENCES OWNER(OID),
    SNAME VARCHAR2(50),
    BLOC VARCHAR2(50),
    BTITLE VARCHAR2(50),
    BCONTENT VARCHAR2(4000),
    BPHOTO1 VARCHAR2(250),
    BPHOTO2 VARCHAR2(250),
    BPHOTO3 VARCHAR2(250),
    BPHOTO4 VARCHAR2(250),
    BPHOTO5 VARCHAR2(250),
    BHIT NUMBER(8),
    BDATE DATE DEFAULT SYSDATE
);
-- BOARD_COMMENT 테이블 생성
CREATE TABLE BOARD_COMMENT(
    CNO NUMBER(8) PRIMARY KEY,
    BNO NUMBER(8) REFERENCES OWNERBOARD(BNO),
    OID VARCHAR2(50) REFERENCES OWNER(OID),
    CCONTENT VARCHAR2(2000),
    CDATE DATE
);