-- RYU DUMMY
COMMIT;
SELECT * FROM STORELIKE;
UPDATE STORE SET oid = 'owner2' WHERE SNO =7 ;
UPDATE STORE SET sconfirm = 'Y' ;
SELECT * FROM STORE;
SELECT * FROM STOREREVIEW;
SELECT * FROM STORE WHERE sno = 6;
DELETE FROM STORE WHERE sno BETWEEN 22 AND 30;
SELECT simage1, sname, slocation, stype, ROUND((sscore/sreplycnt), 1) stscore FROM STORE WHERE sno = 1; -- 가게 평점 
SELECT  GET_STORE_SEQ('sno') FROM DUAL;